version: '3'

services:
  samba:
    image: dperson/samba:rpi
    ports:
      - "139:139/tcp"
      - "445:445/tcp"
    volumes:
      - /mnt/natec:/mount
    command: "-s public;/mount/public;yes;no"

  nordvpn:
    image: pakalucki/nordvpn
    ports:
      - "1194:1194/udp"
    environment:
      username: ${NORDVPN_USER}
      password: ${NORDVPN_PASSWORD}
      protocol: udp
    devices:
      - "/dev/net/tun"
    cap_add:
      - NET_ADMIN
    command: random

  proxy:
    image: pakalucki/proxy
    ports:
      - "8443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    links:
      - "transmission"
    depends_on:
      - "transmission"

  transmission:
    image: linuxserver/transmission:arm32v7-latest
    volumes:
      - /config
      - /watch
      - /mnt/natec/public/torrent/downloads:/downloads
    networks:
      - service:nordvpn
    environment:
      TZ: "Europe/Warsaw"
      USER: ${TRANSMISSION_USER}
      PASS: ${TRANSMISSION_PASS}
    depends_on:
      - "nordvpn"